### ISSUE TITLE
How to save the sql running in postgresql to the query.json

### ISSUE THREAD

**Issue by cobolbaby** [tokern/data-lineage#84]
Could supply the instructions related to the postgresql.

Ref: https://tokern.io/docs/data-lineage/queries

**Comment by vrajat** [comment]
There is no easy way to get query history from postgres or mysql because logging can affect database performance. One option is to set [log_statement](https://www.postgresql.org/docs/current/runtime-config-logging.html#GUC-LOG-STATEMENT) but this will affect database performance.

The other option is to use a proxy like [pgpool](https://www.pgpool.net/docs/latest/en/html/). [Blog on MySQL proxysql](https://tokern.io/blog/proxysql-database-audit/) shows how it can be done for MySQL. A similar approach can be used with pgpool.

**Comment by cobolbaby** [comment]
For `query.json`, I would like to know what fields it should contain. 

@vrajat  Can you clearly give the field definitions of the file, so I can construct the file based on this.
